# NAME: netlify
# BEHAVIOR: domain
# SOURCE: https://github.com/v2fly/domain-list-community/tree/master/data/netlify
# COUNT: 5
# UPDATED: 2025-02-02 21:35:17

payload:
- "+.bitballoon.com"
- "+.netlify.app"
- "+.netlify.com"
- "+.netlifystatus.com"
- "d33wubrfki0l68.cloudfront.net"
